apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy_new_artifact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcafe-nginx
  template:
    metadata:
      name: testcafe-nginx-pod
      labels:
        app: testcafe-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
